app:
  name: "OpenDAX"
  domain: "app.local"
  subdomain: "www"
ssl:
  enabled: false    # Make sure to enable during deployment
  email: "support@example.com"
license:
  url: "https://www.openware.com/api/v2/tenko"
  key: "PASTE-KEY-HERE"
images:
  peatio: rubykube/peatio:2.2.29
  barong: rubykube/barong:2.2.25
  frontend: quay.io/openware/baseapp-lite:2.2.30  # Check on quay.io/openware for latest tags
  tower: quay.io/openware/tower-lite:2.2.8
  postmaster: quay.io/openware/postmaster:2.2.2
vendor:
  frontend: git@github.com:openware/baseapp.git
storage:
  provider: "Google"
  bucketName: "microkube-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
twilio:
  phone_number: "+15005550000"
  account_sid: "changeme"
  auth_token: "changeme"
recaptcha:
  type: "none"
  siteKey: "changeme"
  secretKey: "changeme"
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@postmaster.com
  sender_name: Postmaster
wallets:
  - kind: deposit
    address: "changeme"
    nsig: 1
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: "changeme"
    nsig: 1
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: "changeme"
    nsig: 1
    max_balance: 1000.0
    secret: changeme
terraform:
  credentials: "~/safe/microkube.json"
  project: "example-microkube"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "microkube-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"

